# Generated by Django 3.0.5 on 2022-05-06 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_pizza_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='img',
        ),
    ]
