# Generated by Django 3.0.5 on 2022-05-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_remove_pizza_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='img',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
